# Generated by Django 5.1.7 on 2026-07-13 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('credits', models.IntegerField(default=10)),
            ],
        ),
    ]
