# Generated by Django 5.1.7 on 2026-07-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='credits',
        ),
    ]
